version: '3.8'

networks:
  monitoring-net:
    driver: bridge # private, internal virtual network

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-net
    # Ensures that when
    # Prometheus (inside Docker) tries to scrape 'host.docker.internal',
    # it correctly resolves to your host machine (where your Go app is running).
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring-net
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data: {}