version: '3.8'

networks:
  monitoring-net:
    driver: bridge # private, internal virtual network

services:
  lb:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/cert.pem:/etc/ssl/certs/cert.pem:ro
      - ./config/key.pem:/etc/ssl/keys/key.pem:ro
    networks:
      - monitoring-net
    depends_on:
        - hexgate

  hexgate:
      # build an image using 'Dockerfile' in current dic (.)
      build:
        context: .
        dockerfile: Dockerfile
      networks:
        - monitoring-net
      depends_on:
        - redis
        - consul
      # Add a DNS entry map from host.docker.internal to host machine IP
      extra_hosts:
        - "host.docker.internal:host-gateway"
      environment:
        CONSUL_HTTP_ADDR: "http://consul:8500"
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    command: "agent -dev -client 0.0.0.0"
    networks:
      - monitoring-net

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-net
    depends_on:
      - hexgate

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring-net
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
volumes:
  grafana-data: {}