global:
  scrape_interval: 15s # How often to scrape targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'hexgate'
    static_configs:
      # 'host.docker.internal' is a special DNS name that resolves
      # to the host machine from within a Docker container.
      # Port 8000 is from your config.yaml gatewayPort.
      - targets: ['host.docker.internal:8000']