global:
  scrape_interval: 5s # How often to scrape targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'hexgate'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      # Keep containers on our project's network
      - source_labels: [__meta_docker_network_name]
        regex: hexgate_monitoring-net
        action: keep
      # Keep only containers from the 'hexgate' service
      - source_labels: [ __meta_docker_container_label_com_docker_compose_service ]
        regex: hexgate
        action: keep
      # Scrape on port 8000
      - regex: '.*'
        replacement: $1:8000
        target_label: __address__