global:
  scrape_interval: 5s # How often to scrape targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'hexgate'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      # 'host.docker.internal' is a special DNS name that resolves
      # to the host machine from within a Docker container.
      # Port 8443 is from config.yaml.
      - targets: ['host.docker.internal:8443']