gatewayPort: "8000"
healthCheckInterval: 5 # in seconds
services:
  - name: "user-service"
    path: "/users/"
    consulServiceName: "user-service"
  - name: "product-service"
    path: "/products/"
    consulServiceName: "product-service"
rateLimiting:
  enabled: true
  ratePerSecond: 1   # tokens added per second
  burst: 3
authentication:
  enabled: false
  publicKeyPath: "./config/public.pem"
tls:
  enabled: true
  httpsPort: "8443" # This will be the main HTTPS port
  certFile: "./config/cert.pem"
  keyFile: "./config/key.pem"