gatewayPort: "8000"
healthCheckInterval: 5 # in seconds
services:
  - name: "user-service"
    path: "/users/"
    backends:
      - "http://localhost:8081"
      - "http://localhost:8082"
  - name: "product-service"
    path: "/products/"
    backends:
      - "http://localhost:8083"
rateLimiting:
  enabled: true
  ratePerSecond: 1   # tokens added per second
  burst: 3